# Fabric notebook source

# METADATA ********************

# META {
# META   "kernel_info": {
# META     "name": "synapse_pyspark"
# META   },
# META   "dependencies": {
# META     "lakehouse": {
# META       "default_lakehouse": "b02e4f37-db00-46b2-b745-04f9e1b1e4e7",
# META       "default_lakehouse_name": "Demo_Lakehouse",
# META       "default_lakehouse_workspace_id": "9432ec48-08c3-416e-9b9e-6d54492437c1",
# META       "known_lakehouses": [
# META         {
# META           "id": "b02e4f37-db00-46b2-b745-04f9e1b1e4e7"
# META         }
# META       ]
# META     },
# META     "environment": {
# META       "environmentId": "989fe120-84ab-4e15-8108-734344167a2d",
# META       "workspaceId": "e69bf1bb-2e97-4d8b-8a09-4a8dad9a6ffd"
# META     }
# META   }
# META }

# CELL ********************

import json, notebookutils, time, os, markdown
import sempy_labs as labs
from openai import AzureOpenAI


# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# PARAMETERS CELL ********************

# Parameters cell 
# Activator / pipelines can override these at run time.

workspace_id = "e69bf1bb-2e97-4d8b-8a09-4a8dad9a6ffd"
item_id = "913e50e8-3258-496c-942f-647e37803efc"             # semantic model GUID
event_text = "EVALUATE {COUNTROWS(mv_base)}"

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

aad_token = notebookutils.credentials.getToken("https://cognitiveservices.azure.com/.default")

client = AzureOpenAI(
    azure_endpoint="<YourAzureOpenAIEndpoint>",
    azure_ad_token=aad_token,
    api_version="2024-12-01-preview",
)

DEPLOYMENT = "gpt-5.4-mini"   # your deployment name

workspace_id = workspace_id.strip()
item_id = item_id.strip()

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

def ask_llm(system: str, user: str) -> str:
    resp = client.chat.completions.create(
        model=DEPLOYMENT,
        messages=[
            {"role": "system", "content": system},
            {"role": "user",   "content": user},
        ],
        temperature=0.2,
    )
    return resp.choices[0].message.content

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

bpa = labs.run_model_bpa(dataset=item_id, workspace=workspace_id, return_dataframe=True)
display(bpa)

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

bpa_severe = bpa[bpa["Severity"] == "⚠️"]

bpa_payload = bpa_severe.to_markdown(index=False)

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

vertipaq = labs.vertipaq_analyzer(dataset=item_id, workspace=workspace_id)

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

tables = vertipaq["Tables"][["Table Name", "Type", "Row Count", "Columns", "% DB"]]
columns = vertipaq["Columns"][["Table Name", "Column Name", "Type", "Cardinality", "Data Type", "% DB"]]
relationships = vertipaq["Relationships"][["From Object", "To Object", "Multiplicity"]]

table_payload = tables.to_markdown(index=False)
column_payload = columns.to_markdown(index=False)
relationship_payload = relationships.to_markdown(index=False)

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

SYSTEM = """You are a senior data architect specializing in Power BI Semantic Model optimization.
You receive Best Practice Analyzer findings, VertiPaq memory statistics, and a query that takes too long to run.
Produce:
1. A prioritized list of the top 10 optimizations, ordered by potential performance impact (high to low).
2. For each: the concrete fix. Make sure the fix is explicitly related to the query that was generated by the engine. No need to boil the ocean here.
3. A short section on memory hot spots and which columns to drop, change cardinality, or switch to integer keys.
Be terse. No filler. Use markdown headings. Don't include the original query/event text in your response - they are usually too long."""

user_msg = f"""
# Query
{event_text}

# BPA findings (failed rules only)
{bpa_payload}

# Vertipaq analyzer results 
## Tables
{table_payload}

## Columns
{column_payload}

## Relationships
{relationship_payload}
"""

review = ask_llm(SYSTEM, user_msg)
print(review)

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

timestamp = int(time.time())

file_name = f"{item_id}_{timestamp}.json"
json_path = f"/lakehouse/default/Files/Optimizer/{file_name}"

os.makedirs(os.path.dirname(json_path), exist_ok=True)

html_body = markdown.markdown(
    review,
    extensions=["tables", "fenced_code", "sane_lists", "toc"],
)

# Wrap with inline CSS so it looks decent in Outlook (which strips <style> aggressively
# but does respect inline styles and very basic <style> blocks).
html_doc = f"""<!doctype html>
<html><head><meta charset="utf-8">
<style>
  body {{ font-family: Segoe UI, Arial, sans-serif; font-size: 14px; color: #222; }}
  h1, h2, h3 {{ color: #1f3864; }}
  table {{ border-collapse: collapse; margin: 8px 0; }}
  th, td {{ border: 1px solid #ccc; padding: 4px 8px; text-align: left; }}
  th {{ background: #f2f2f2; }}
  code {{ background: #f4f4f4; padding: 1px 4px; border-radius: 3px; }}
  pre {{ background: #f4f4f4; padding: 8px; border-radius: 4px; overflow-x: auto; }}
</style></head>
<body>
{html_body}
</body></html> 
"""

payload = {
    "status": "ok",
    "report_path": f"{json_path}",
    "file_name": f"{item_id}_{timestamp}.json",
    "html": html_doc
}

with open(json_path, "w", encoding="utf-8") as f:
    f.write(json.dumps(payload, ensure_ascii=False))

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

notebookutils.notebook.exit(json.dumps({"file_name": file_name}))

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }
